package criteriav2_test

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"

	criteriav2 "github.com/brokenbots/criteria-adapter-proto/criteria/v2"
)

// The digest vectors in this file were generated by running the Criteria
// host's implementation (internal/adapter/audit/canonical.go) and this
// module's criteriav2.CanonicalJSON/ArgsDigest side by side over a matrix of
// raw JSON documents and Go-native values; both produced byte-identical
// output for every input. The committed vectors below are those host-computed
// values, so any drift in the SDK port (or a future refactor of the shared
// algorithm) fails here before it can desynchronise args_digest parity
// (asserted by CRI-154, consumed by CRI-164).

// TestCanonicalJSON pins the canonical encoding: byte-exact output for raw
// JSON documents (parsed with encoding/json) and Go-native values.
func TestCanonicalJSON(t *testing.T) {
	tests := []struct {
		name   string
		input  string // raw JSON; empty means use the Go-native value instead
		native any
		want   string
	}{
		{"empty object", `{}`, nil, `{}`},
		{"empty array", `[]`, nil, `[]`},
		{"null", `null`, nil, `null`},
		{"true", `true`, nil, `true`},
		{"false", `false`, nil, `false`},
		{"integer float", `1.5`, nil, `1.5`},
		{"exponent expands", `1e7`, nil, `10000000`},
		// encoding/json strips the leading zero from two-digit negative
		// exponents ("1e-07" -> "1e-7"), which happens to match ES6 here;
		// the format itself is Go's, not RFC 8785's ES6 algorithm.
		{"small exponent go format", `1e-7`, nil, `1e-7`},
		{"large exponent go format", `1e21`, nil, `1e+21`},
		{"negative exponent tiny", `1e-21`, nil, `1e-21`},
		{"float64 precision", `12345678901234567890`, nil, `12345678901234567000`},
		{"negative zero kept", `-0`, nil, `-0`},
		{"fraction stays full", `0.30000000000000004`, nil, `0.30000000000000004`},
		{"plain string", `"plain"`, nil, `"plain"`},
		{"string escapes", `"quote\"inside"`, nil, `"quote\"inside"`},
		{"backslash and newline", `"backslash\\and newline\n"`, nil, `"backslash\\and newline\n"`},
		// encoding/json HTML-escapes <, >, & — a deliberate deviation from
		// RFC 8785 that is part of the pinned parity contract.  The want
		// strings are back-quoted so the \uXXXX sequences stay literal.
		{"html escaping", `"html<&>chars"`, nil, `"html\u003c\u0026\u003echars"`},
		{"unicode passes through", `"unicode ☃ snowman"`, nil, `"unicode ☃ snowman"`},
		{"u2028 u2029 escaped", "\"u2028\u2028u2029\u2029line-seps\"", nil, `"u2028\u2028u2029\u2029line-seps"`},
		{
			"keys sorted byte-wise",
			`{"z":1,"a":2,"M":3,"_":4,"0":5,"é":6,"☃":7}`,
			nil,
			`{"0":5,"M":3,"_":4,"a":2,"z":1,"é":6,"☃":7}`,
		},
		{
			"nested containers",
			`{"b":{"d":4,"c":[1,2,{"y":1,"x":2}]},"a":1}`,
			nil,
			`{"a":1,"b":{"c":[1,2,{"x":2,"y":1}],"d":4}}`,
		},
		{"mixed array", `[1,"two",null,false,{"k":"v"},[9,8]]`, nil, `[1,"two",null,false,{"k":"v"},[9,8]]`},
		{"empty key sorts first", `{"":"empty key","a":"dup risk"}`, nil, `{"":"empty key","a":"dup risk"}`},
		{
			"deep nesting",
			`{"deep":{"a":{"b":{"c":{"d":{"e":["x","y",{"f":true}]}}}}}}`,
			nil,
			`{"deep":{"a":{"b":{"c":{"d":{"e":["x","y",{"f":true}]}}}}}}`,
		},
		{
			"go native map and slice",
			"",
			map[string]any{"beta": 2.5, "alpha": "a", "gamma": []any{true, nil, 3.0}},
			`{"alpha":"a","beta":2.5,"gamma":[true,null,3]}`,
		},
		{
			"go native struct fields sorted",
			"",
			struct {
				Tool string         `json:"tool"`
				Args map[string]any `json:"args"`
			}{Tool: "create_issue", Args: map[string]any{"title": "T", "count": 2.0}},
			`{"args":{"count":2,"title":"T"},"tool":"create_issue"}`,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			var v any
			if tc.input != "" {
				require.NoError(t, json.Unmarshal([]byte(tc.input), &v))
			} else {
				v = tc.native
			}

			got, err := criteriav2.CanonicalJSON(v)
			require.NoError(t, err)
			assert.Equal(t, tc.want, string(got))
			assert.NotContains(t, string(got), "\n", "canonical output must not contain raw newlines")
		})
	}
}

// TestCanonicalJSON_InputKeyOrderIrrelevant verifies the whole point of the
// canonical form: different input key orders produce identical bytes and
// digests, so audit trails and correlation compare equal across
// serialisation-order differences.
func TestCanonicalJSON_InputKeyOrderIrrelevant(t *testing.T) {
	one, err := criteriav2.CanonicalJSON(map[string]any{"a": 1.0, "b": 2.0, "c": map[string]any{"z": 1.0, "y": 2.0}})
	require.NoError(t, err)
	two, err := criteriav2.CanonicalJSON(map[string]any{"c": map[string]any{"y": 2.0, "z": 1.0}, "b": 2.0, "a": 1.0})
	require.NoError(t, err)

	assert.Equal(t, string(one), string(two))

	d1, err := criteriav2.ArgsDigest(map[string]any{"a": 1.0, "b": 2.0, "c": map[string]any{"z": 1.0, "y": 2.0}})
	require.NoError(t, err)
	d2, err := criteriav2.ArgsDigest(map[string]any{"c": map[string]any{"y": 2.0, "z": 1.0}, "b": 2.0, "a": 1.0})
	require.NoError(t, err)
	assert.Equal(t, d1, d2)
}

// TestArgsDigest_HostParityVectors pins ArgsDigest to digests computed by the
// Criteria host's implementation over the same inputs (see file comment).
// These cover the scalar, string-escaping, float-formatting, key-sorting,
// nesting, and adapter-tool-call shapes that CRI-152's args_digest rides on.
func TestArgsDigest_HostParityVectors(t *testing.T) {
	tests := []struct {
		name       string
		input      string // raw JSON; empty means use the Go-native value instead
		native     any
		wantDigest string
	}{
		{"empty object", `{}`, nil, "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"},
		{"empty array", `[]`, nil, "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"},
		{"null", `null`, nil, "74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b"},
		{"small exponent go format", `1e-7`, nil, "5b33e02f2c5103a05d32f6ba9cb058294452bfbf393967f68bb30c1bdcbbab22"},
		{"html escaping", `"html<&>chars"`, nil, "9f4010548524be217ca3539249cc528d9b067ba7de07c095271f80df4553b75a"},
		{"unicode passes through", `"unicode ☃ snowman"`, nil, "9d9a5c2f1aca16ca4978530c381aa4a58db0a8ed2baf766db03a4aa1e9645398"},
		{"byte-wise key sort", `{"z":1,"a":2,"M":3,"_":4,"0":5,"é":6,"☃":7}`, nil, "b741b73ebe81afe9d2a8c00617ce3ebadfb5bd1bf031142863056361f1abf8a3"},
		{"nested containers", `{"b":{"d":4,"c":[1,2,{"y":1,"x":2}]},"a":1}`, nil, "a93275b484a96df365c78234c327323850c9f5d6cee140fc296b26ae7450956f"},
		{"float64 precision", `12345678901234567890`, nil, "afdcd3321a2fcdb3414cb69a0c92c6bb8d74c06066d721083cc01fec664ab97f"},
		{"go native struct", "", struct {
			Tool string         `json:"tool"`
			Args map[string]any `json:"args"`
		}{Tool: "create_issue", Args: map[string]any{"title": "T", "count": 2.0}},
			"7c869fd97b0d13b6081238b94183ecaf7cf1611b04586cc6d14d9567230910a9"},
		{"adapter tool call args", `{"adapter":"github","tool":"create_issue","args":{"title":"T","body":"B","labels":["p1","p2"],"draft":false}}`, nil,
			"66b19796b64efff0e606607318cc389ca57d066067e8bac1a5967667930a85c2"},
		{"adapter tool args realistic", "",
			map[string]any{
				"owner":  "octocat",
				"repo":   "hello-world",
				"title":  "Found a bug",
				"body":   "I'm having a problem with this.",
				"labels": []any{"bug", "help wanted"},
				"draft":  false,
			},
			"7a8cfc10662c078da696d5b3f4574c830a2aa3e5a675f3d4d0086f1bf9d5ff11"},
		{"adapter tool args nested", "",
			map[string]any{
				"config": map[string]any{"retries": 3.0, "timeout_ms": 1500.5, "flags": []any{true, false}},
				"id":     "req-123",
			},
			"9d85fdfad7cbc6f66da717261972f7bda1e76fce9b5f730a6ceb4e56ee98b7e5"},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			var v any
			if tc.input != "" {
				require.NoError(t, json.Unmarshal([]byte(tc.input), &v))
			} else {
				v = tc.native
			}

			got, err := criteriav2.ArgsDigest(v)
			require.NoError(t, err)
			assert.Equal(t, tc.wantDigest, got)
			assert.Len(t, got, 64, "sha256 hex digest is 64 lowercase hex chars")
		})
	}
}

// TestArgsDigest_MatchesCanonicalJSONSHA256 verifies the digest is exactly
// sha256 over the canonical bytes, not over some other serialisation.
func TestArgsDigest_MatchesCanonicalJSONSHA256(t *testing.T) {
	v := map[string]any{"tool": "create_issue", "args": map[string]any{"n": 1.0, "s": "x"}}

	canon, err := criteriav2.CanonicalJSON(v)
	require.NoError(t, err)

	digest, err := criteriav2.ArgsDigest(v)
	require.NoError(t, err)

	sum := sha256.Sum256(canon)
	assert.Equal(t, hex.EncodeToString(sum[:]), digest)
}

// TestCanonicalJSON_UnsupportedTypeErrors verifies the error path: values
// that cannot be marshalled to JSON fail with an error instead of producing
// garbage bytes.
func TestCanonicalJSON_UnsupportedTypeErrors(t *testing.T) {
	_, err := criteriav2.CanonicalJSON(map[string]any{"ch": make(chan int)})
	assert.Error(t, err)
}

// TestArgsDigest_ToolCallParityWithPermissionRequest pins the CRI-154
// args_digest parity contract across the two wire surfaces that carry a
// tool call's digest:
//
//   - PermissionRequest.args_digest on the Permissions stream (the host
//     asks the adapter to approve the call), and
//   - the "args_digest" key of the permission.request AdapterEvent payload
//     with kind "adapter_tool" on the Execute stream (the SDK reports the
//     call to the host for permission evaluation).
//
// Both surfaces must hold the same sha256(canonical_json(args)) value,
// computed by the exported helper criteriav2.ArgsDigest, so that host-side
// correlation and audit compare equal no matter which surface a consumer
// observes, and recomputing the digest from the reported args reproduces it.
//
// Vector source: the canonical bytes below are hand-pinned shared vectors in
// the host's canonical-JSON dialect (byte-wise key sort, no whitespace,
// encoding/json string escaping — the same dialect pinned by
// TestCanonicalJSON above); each digest is sha256 over exactly those bytes,
// matching the engine's implementation (internal/adapter/audit/canonical.go,
// cross-checked side by side per the file-comment methodology above).
func TestArgsDigest_ToolCallParityWithPermissionRequest(t *testing.T) {
	const tool = "create_issue"
	vectors := []struct {
		name       string
		argsJSON   string // raw JSON of the call args, as the calling adapter holds them
		wantCanon  string // pinned canonical JSON, shared with the host
		wantDigest string // pinned sha256(canonical JSON), shared with the host
	}{
		{
			name:       "flat args, key order differs from canonical",
			argsJSON:   `{"title":"Found a bug","labels":["bug","help wanted"]}`,
			wantCanon:  `{"labels":["bug","help wanted"],"title":"Found a bug"}`,
			wantDigest: "1ad0cfd63d392e1498cc20c961665b51f9595916fa6f74d6fc201eeeae1d34e9",
		},
		{
			name:       "nested args, nested key order differs too",
			argsJSON:   `{"draft":false,"repo":"hello-world","owner":"octocat","config":{"timeout_ms":1500.5,"retries":3}}`,
			wantCanon:  `{"config":{"retries":3,"timeout_ms":1500.5},"draft":false,"owner":"octocat","repo":"hello-world"}`,
			wantDigest: "fc795b0731cf8ee1c9b55c4cf19d7c320e7066d92043804b9df3f192f8a4af0d",
		},
		{
			name:       "args containing HTML-escapable characters",
			argsJSON:   `{"body":"a<b>&c"}`,
			wantCanon:  `{"body":"a\u003cb\u003e\u0026c"}`,
			wantDigest: "4299b4663303acff818fd993e0cabd98949de46231b7de58fa5808087ba2834a",
		},
		{
			name:       "empty args object",
			argsJSON:   `{}`,
			wantCanon:  `{}`,
			wantDigest: "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
		},
	}
	for _, tc := range vectors {
		t.Run(tc.name, func(t *testing.T) {
			var args any
			require.NoError(t, json.Unmarshal([]byte(tc.argsJSON), &args))

			// The exported helper (CRI-152) produces exactly the pinned
			// canonical bytes and their digest.
			canon, err := criteriav2.CanonicalJSON(args)
			require.NoError(t, err)
			assert.Equal(t, tc.wantCanon, string(canon), "canonical bytes must match the shared vector")
			digest, err := criteriav2.ArgsDigest(args)
			require.NoError(t, err)
			assert.Equal(t, tc.wantDigest, digest, "args_digest must match the shared vector")

			// The digest is exactly sha256 over the canonical bytes — the
			// documented formula, not some other serialisation.
			sum := sha256.Sum256([]byte(tc.wantCanon))
			assert.Equal(t, hex.EncodeToString(sum[:]), digest)

			// Wire parity: the SAME digest string rides both surfaces.
			//
			// Permissions stream, adapter→host:
			req := &criteriav2.PermissionRequest{
				RequestId:  "req-parity-1",
				Tool:       tool,
				ArgsDigest: digest,
			}
			reqBytes, err := proto.Marshal(req)
			require.NoError(t, err)
			var onPermissions criteriav2.PermissionRequest
			require.NoError(t, proto.Unmarshal(reqBytes, &onPermissions))

			// Execute stream, permission.request AdapterEvent payload
			// (kind "adapter_tool"), in its documented map form.
			payload := map[string]any{
				"kind":        "adapter_tool",
				"request_id":  req.RequestId,
				"target":      "adapter.github.octocat.tools." + tool,
				"tool":        tool,
				"args":        args,
				"args_digest": digest,
			}
			payloadJSON, err := json.Marshal(payload)
			require.NoError(t, err)
			var onExecute map[string]any
			require.NoError(t, json.Unmarshal(payloadJSON, &onExecute))

			assert.Equal(t, onPermissions.GetArgsDigest(), onExecute["args_digest"],
				"PermissionRequest.args_digest and the adapter_tool payload args_digest must be the same digest")

			// Recomputing the digest from the payload's args (serialized in
			// whatever key order json.Marshal chose) reproduces the wire
			// digest: canonicalisation makes correlation order-insensitive.
			recomputed, err := criteriav2.ArgsDigest(onExecute["args"])
			require.NoError(t, err)
			assert.Equal(t, onPermissions.GetArgsDigest(), recomputed,
				"digest recomputed from the payload args must match the wire digest")
		})
	}

	// Serialisation-order independence on the args themselves: two adapters
	// holding the same args in different map orders digest identically, so
	// parity never depends on insertion order.
	d1, err := criteriav2.ArgsDigest(map[string]any{"title": "T", "body": "B", "labels": []any{"bug", "p1"}, "draft": false})
	require.NoError(t, err)
	d2, err := criteriav2.ArgsDigest(map[string]any{"draft": false, "labels": []any{"bug", "p1"}, "body": "B", "title": "T"})
	require.NoError(t, err)
	assert.Equal(t, d1, d2, "same args in different map orders must digest identically")
}
